apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  #- harbor/application.yaml
  - vault/application.yaml
  - envoy-gateway
  - metallb
  - kubernetes-dashboard
  - local-path-provisioner/application.yaml
  - cert-manager/application.yaml