apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/rancher/local-path-provisioner.git
      targetRevision: v0.0.32
      path: deploy/chart/local-path-provisioner
      helm:
        releaseName: local-path-provisioner
        valueFiles:
          - $values/argocd/platform/local-path-provisioner/values.yaml
    - repoURL: https://github.com/dinosgnk/homelab.git
      targetRevision: main
      ref: values
        
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
